services:
  app:
    build: .
    container_name: WIAMS2
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    depends_on:
      - db
    networks:
      - app_network

  webserver:
    image: nginx:latest
    container_name: WIAMS2_webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./storage:/var/www/storage
    depends_on:
      - app
    networks:
      - app_network

  db:
    image: mysql:5.7
    container_name: WIAMS_db2
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: WIAMS2
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306" 
    networks:
      - app_network

networks:
  app_network:

volumes:
  db_data:
